{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Marca:\n",
    "    def __init__(self, nombre):\n",
    "        self.nombre=nombre\n",
    "    def getNombre(self):\n",
    "        return self.nombre\n",
    "class TV:\n",
    "    numTV=0\n",
    "    def __init__(self, marca, estado):\n",
    "        self.marca=marca\n",
    "        self.estado=estado\n",
    "        self.control=control\n",
    "        precio=500\n",
    "        volumen=1\n",
    "        canal=1\n",
    "        numTV = numTV + 1\n",
    "    def getMarca():\n",
    "        return marca\n",
    "    def setMarca(self, marca):\n",
    "        self.marca=marca\n",
    "    def getControl(self):\n",
    "        return control\n",
    "    def setControl(self, control):\n",
    "        self.control=control\n",
    "    def getPrecio(self):\n",
    "        return precio\n",
    "    def setPrecio(self, precio):\n",
    "        self.precio=precio\n",
    "    def getVolumen(self):\n",
    "        return volumen\n",
    "    def setVolumen(self, volumen):\n",
    "        if ((estado == true) and (volumen <8 and volumen >0)):\n",
    "            self.volumen=volumen\n",
    "    def getCanal(self):\n",
    "        return canal\n",
    "    def setCanal(self, canal):\n",
    "        self.canal=canal\n",
    "    def getnumTV(self):\n",
    "        return numTV\n",
    "    def turnOn(self):\n",
    "        if estado ==False:\n",
    "            estado = True\n",
    "    def turnOff(self):\n",
    "        if estado ==True:\n",
    "            estado = False\n",
    "    def canalUp(self, canal):\n",
    "        if (canal > 0 and canal <= 120)and(estado==True):\n",
    "            canal+=1\n",
    "    def canalDown(self, canal):\n",
    "        if (canal > 1 and canal < 121)and(estado==True):\n",
    "            canal-=1\n",
    "    def volumenUp(self, volumen):\n",
    "        if (volumen >=0 and volumen <=7)and(estado==True):\n",
    "            volumen+=1\n",
    "    def volumenDown(self, volumen):\n",
    "        if (volumen < 8 and volumen >=0)and(estado == True):\n",
    "            volumen-=1\n",
    "    def getEstado(self):\n",
    "        return estado\n",
    "    \n",
    "\n",
    "class Control:\n",
    "    \n",
    "    def __init__(self):\n",
    "        self.tv=None\n",
    "def turnOn(self):\n",
    "    self.tv.turnOn()\n",
    "def turnOff(self):\n",
    "    self.tv.turnOff()\n",
    "def canalUp(self):\n",
    "    self.tv.canalUp()\n",
    "def canalDown(self):\n",
    "    self.tv.canalDown()\n",
    "def volumenUp(self):\n",
    "    self.tv.volumenUp()\n",
    "def volumenDown(self):\n",
    "    self.tv.volumenDown()\n",
    "def setCanal(self,can):\n",
    "    self.tv.setCanal(can)\n",
    "def enlazar(self, tele):\n",
    "    self.tv=tele\n",
    "    TV.setControl(tele)\n",
    "def getTv(self):\n",
    "    return tv\n",
    "def setTv(self, tv):\n",
    "    self.tv=tv"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.6 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.6"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "7579aee364a2e290dfc6a620616239004625e0c1356cc42c7bb47894a11803af"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
